name: Expo Publishing
on:
  push:
    branches:
      - master
jobs:
  setup-pandoc:
    name: Setup pandoc
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.9.2'
      - run: echo "# Test" | pandoc -t html
      - name: convert docx to html
        run: |
          Get-ChildItem -Path ".\docs" -Filter *.docx | ForEach-Object { pandoc -s --self-contained --track-changes=accept --quiet -f docx+styles -t html -o ($_.FullName + '.html') $_.FullName }
          Get-ChildItem -Path ".\docs" -Filter *.html | Rename-Item -NewName { $_.name -replace " ","_" }
          Get-ChildItem -Path ".\docs\*.html" -Recurse | Move-Item -Destination ".\www"
        shell: powershell   
