name: Expo Publishing
on:
  push:
    branches:
      - master
jobs:
  setup-pandoc:
    name: Setup and run pandoc
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.9.2'
      - run: echo "# Test" | pandoc -t html
  publish:
    name: Install and publish
    needs: [setup-pandoc]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - run: yarn install
      - run: expo publish
